spring:
  data:
    redis:
      host: ${REDIS_HOST:redis-cluster}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

app:
  api:
    rate-limit:
      enabled: true
      requests-per-minute: 2000
    cors:
      allowed-origins: "${ALLOWED_ORIGINS:https://yourdomain.com}"
  
  queue:
    threshold:
      max-concurrent-requests: 1000
    max-queue-size: 1000000

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster:9092}

redisson:
  address: "redis://${REDIS_HOST:redis-cluster}:${REDIS_PORT:6379}"
  password: ${REDIS_PASSWORD:}

logging:
  level:
    root: WARN
    com.ticketing: INFO
  file:
    name: logs/ticket-api.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
