spring:
  application:
    name: ticket-api

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        # 버퍼 메모리 증가 (기본 32MB)
        buffer.memory: 67108864 
        # 전송 대기 시간 (기본 0ms)
        linger.ms: 20
        # 최대 블로킹 시간 (기본 60초)
        max.block.ms: 30000
        # 멱등성 Producer 활성화
        enable.idempotence: true
    consumer:
      group-id: ticket-queue-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      fetch-min-size: 1
      fetch-max-wait: 100
      max-poll-records: 1
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
        max.poll.interval.ms: 30000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms

# Redisson 설정 추가
redisson:
  file: classpath:redisson.yaml

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ticketing.ticketapi: INFO
    org.springframework.web: INFO
    org.redisson: INFO

app:
  api:
    cors:
      allowed-origins: "*"
    rate-limit:
      enabled: true
      requests-per-minute: 1000
  
  queue:
    kafka:
      topic: ticket-requests
      partitions: 3
      replication-factor: 1
    threshold:
      max-concurrent-requests: 100
      check-interval-ms: 1000
    token:
      expiry-minutes: 30
  
  scheduler:
    queue-admission:
      enabled: true
