app:
  api:
    rate-limit:
      enabled: false
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:8080"
  
  queue:
    threshold:
      max-concurrent-requests: 5

logging:
  level:
    com.ticketing: DEBUG
    org.springframework.web: DEBUG
