spring:
  application:
    name: ticket-api
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  kafka:
    consumer:
      group-id: ticket-queue-group
      fetch-min-size: 1
      fetch-max-wait: 100
      max-poll-records: 1

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# === 모니터링 설정 ===
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# === API 전용 설정 ===
app:
  api:
    cors:
      allowed-origins: "*"
    rate-limit:
      enabled: true
      requests-per-minute: 1000
  
  scheduler:
    queue-admission:
      enabled: true

logging:
  level:
    com.ticketing.ticketapi: INFO
    org.springframework.web: INFO
