spring:
  application:
    name: ticket-system
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          password: null
          database: 0
          timeout: 3000
          connectionPoolSize: 20
          connectionMinimumIdleSize: 5
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          retryAttempts: 3
          retryInterval: 1500

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      properties:
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
        max.poll.interval.ms: 30000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000

app:
  queue:
    threshold:
      max-concurrent-requests: 100
      check-interval-ms: 1000
    max-queue-size: 100000
    admission-batch-size: 100
    admission-interval-seconds: 10
    token:
      expiry-minutes: 30
    kafka:
      topic: ticket-requests
      partitions: 3
      replication-factor: 1
    lock:
      wait-time-seconds: 10
      lease-time-seconds: 30

  redis:
    queue-key: "waiting:queue"
    user-session-prefix: "user:session:"
    ttl-seconds: 1800  # 30분

  kafka:
    topics:
      user-admitted: user-admitted-topic
      ticket-reserved: ticket-reserved-topic
      payment-completed: payment-completed-topic
    enabled: true

utils:
  encryption:
    algorithm: AES
    key-length: 256
  date:
    timezone: Asia/Seoul
    format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.ticketing: INFO
    org.springframework.kafka: WARN
    org.springframework.data.redis: WARN
    org.redisson: INFO
