spring:
  application:
    name: ticket-common

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
    consumer:
      group-id: ticket-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.ticketing.ticketcommon.kafka.event"

app:
  kafka:
    topics:
      user-admitted: user-admitted-topic
      ticket-reserved: ticket-reserved-topic
      payment-completed: payment-completed-topic
    enabled: false

utils:
  encryption:
    algorithm: AES
    key-length: 256
  date:
    timezone: Asia/Seoul
    format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.ticketing.ticketcommon: INFO
    org.springframework.kafka: WARN
